### ISSUE TITLE
MSVC 11 compile error

### ISSUE THREAD

**Issue by jmckenna** [winlibs/libiconv#5]
With master, the following error is thrown (using /MSVC11/libiconv.sln):
```
error C2632: 'int' followed by 'int' is illegal	
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\wchar.h	
line#1202
```

Not sure what has changed here recently, as the MSVC11 build was working fine before.

**Comment by jmckenna** [comment]
It looks like the source (vanilla libiconv-1.15) was recently copied here, 3 months ago, upgraded from 1.14, so maybe one of those changes is causing this?

**Comment by jmckenna** [comment]
If suddenly your answer is now "sorry jeff we no longer support VC11" then can you please remove the folder /MSVC11/ from master? Because I have been relying on that.  If you remove it in master then someone else other than me won't be stuck here at this hard wall.  Thanks.

**Comment by weltling** [comment]
@jmckenna you're right, only the projects updated are vc14 and above. As vc11 is only useful for PHP 5, but the latest stable release is in security mode only, we won't be able to touch deps there. At least as long as there is no security impact. For 5.6, it's better to continue to use libiconv-1.14 from the tag, as 1.15 is also not tested with PHP 5. Alternatively, if one would backport solutions to vc11 or even lower, I'd only welcome it. Otherwise indeed should remove the unsupported solutions and retag.

Thanks.

**Comment by weltling** [comment]
The incompatible projects are removed before tag libiconv-1.15-1.

Thanks.
